### ISSUE TITLE
Usability issue editing interactive video 

### ISSUE THREAD

**Issue by Gpakat** [h5p/h5p-course-presentation#1]
When editing an interactive video as part of a course presentation (place on a slide) clicking on Done does result in saving the changes for the interactive video but the Editor screen persists and does not go away (internet explorer 11). When the whole Course presentation is saved all changes have been made. This is a major usability issue in Course Presentation. Other content types can be saved and the editor screen disappears and work can be continued without Saving the whole presentation first.

**Comment by falcon-git** [comment]
Thanks for reporting. This has been fixed in Coursepresentation 1.4
