### ISSUE TITLE
Change styles of yours packages

### ISSUE THREAD

**Issue by oghmios** [h5p/h5p-course-presentation#13]
Hi,
First of all, thank you for that incredible framework.

My question is, can I change, for example, the css of one of your components( like course presentation) and upload to drupal to use with my changes and create new content?

**Comment by falcon-git** [comment]
Hi,

Yes, this is fully possible. Does this help?
https://h5p.org/documentation/for-developers/visual-changes

**Comment by oghmios** [comment]
and with that can I change for example,  the slide buttons that you are create?

**Comment by falcon-git** [comment]
Yes, you can add any css changes.
