### ISSUE TITLE
French localisation has no "defaults" translation

### ISSUE THREAD

**Issue by jtesse** [h5p/h5p-course-presentation#14]
I translate it.
[fr.json.txt](https://github.com/h5p/h5p-course-presentation/files/40885/fr.json.txt)

**Comment by icc** [comment]
Thank you, I've updated the translation and it works beautifully! It will be part of the upcoming release.

To make it easier in the future, you can use the *Edit this file* button in the upper right corner of [fr.json](https://github.com/h5p/h5p-course-presentation/blob/master/language/fr.json). This will automatically create a *fork*. When you're done making your changes you simply press the *pull request* button, and we will add you changes.

Thanks again for contributing!
