### ISSUE TITLE
Missing required library H5P.InteractiveVideo 1.26

### ISSUE THREAD

**Issue by thibsy** [h5p/h5p-course-presentation#313]
Hi folks,

I run into an issue when trying to install the latest version of the course presentation content type, downloaded from the H5P hub. The `H5PValidator` aborts with the message `Missing required library H5P.InteractiveVideo 1.26`. I searched the downloaded library file and there seems to be an `H5P.InteractiveVideo-1.27` folder. Maybe the right version has been "packed" but the wrong one has been referenced somewhere (or vice-versa)?

Kind regards,
@thibsy

**Comment by Charly66** [comment]
It looks like the issue comes from [h5p-editor-course-presentation](https://github.com/h5p/h5p-editor-course-presentation).
Where the editor needed H5P.InteractiveVideo 1.26 to run in file : [https://github.com/h5p/h5p-editor-course-presentation/blob/master/library.json](https://github.com/h5p/h5p-editor-course-presentation/blob/master/library.json)
`    {
      "machineName": "H5P.InteractiveVideo",
      "majorVersion": 1,
      "minorVersion": 26
    },
`

**Comment by Charly66** [comment]
I've create a PR on the repo : https://github.com/h5p/h5p-editor-course-presentation/pull/99

**Comment by Charly66** [comment]
It look like the update has already been done in tag 1.25.14 but the H5P.CoursePresentation loads the 1.25.13 version of H5PEditor.CoursePresentation.
@fnoks Is it possible to upgrade master branch of H5PEditor.CoursePresentation to the last tag ? https://github.com/h5p/h5p-editor-course-presentation/tree/1.25.14

**Comment by Charly66** [comment]
Jira also created : https://h5ptechnology.atlassian.net/browse/HFP-4149

**Comment by darius-m** [comment]
@fnoks have you had any chances to look into this? We're still getting the `Missing required library H5P.InteractiveVideo 1.26` error and course presentation cannot be installed.

**Comment by fnoks** [comment]
This is now fixed on h5p.org. I am sorry it took some time!
