### ISSUE TITLE
Pull Request: CoursePresentation Social Media Sharing

### ISSUE THREAD

**Issue by adam-p-king** [h5p/h5p-course-presentation#38]
# CoursePresentation Social Sharing

As I'm sure you're aware, social media sharing upon completion of a CoursePresentation currently only has the option for sharing with Twitter. I have modified the library to support Facebook, Google+ and added a couple more options for Twitter following the standard set by the SummarySlide prototype: `addTwitterScoreLinkTo()`.

## Settings
The administrator is able to modify what is shared by default using the `Behaviour settings` menu whilst in the Course Presentation editor.

### Twitter
| **Option** | **Description** | 
|:------------:|------------------|
| Share to Twitter statement | The text to fill the Twitter share textarea with. |
| Share to Twitter link | A link to place after the share statement, before the hashtags |
| Share to Twitter hashtags   | A comma-separated list of hashtags to place at the end of the textarea. | 

### Facebook
| **Option** | **Description** | 
|:------------:|------------------|
| Share to Facebook Link | A link to a relevant landing page for the public |
| Share to Facebook Title | The title to place on the link in the post |
| Share to Facebook Description | The text to place in the shared link area as a description |
| Share to Facebook Quote | Text to place into a  styled Facebook quote |

### Google+
| **Option** | **Description** |
|:------------:|-------------------|
| Share to Google Link | The link to direct the public to when shared |

### Placeholders (To be used in the above settings)
| **Placeholder** | **Description** |
|:-----------------:|-------------------|
| @percentage | The score percentage earned during the CoursePresentation |
| @url | The url of the current page the H5P is on |

### Facebook App Id
A Facebook App Id has been discussed before and has more to think about than merely creating a shell Facebook Application to allow everyone to implement with. Rate limits from Facebook seem to be fairly forgiving, although this does not mean future planning should not take place; given that this is a public utility and may be hosted from multiple locations, I would suggest creating an ID on a per-library basis, especially in the event that Facebook change their rate limits. 

### Context Privacy
Obviously for paid or closed platforms, sharing a direct link to the H5P can be an issue and prevent people from using the `@url` placeholder. You can, however, provide a URL to a location other than the specific course,lesson or resource the H5P is located in, allowing users to be pointed towards a useful or resourceful place to learn more about the service. This may be, for example, a shop front in which you can buy the resource somebody else shared their H5P progress for.

**Comment by falcon-git** [comment]
Thank you for providing this quite thorough pull request. I assume that you're considering to provide a pull-request for this, which would be really great! More social media sharing and especially  Facebook has been requested by the community multiple times.

Do you plan to add settings for toggling the different social sharing options on or off? I think we should get that in from the start.

Regarding the texts, they probably shouldn't be under localization. Texts there are the same for all Course Presentations in one H5P. The texts for social sharing probably could vary from presentation to presentation. Right now the only way to have multiple Course Presentations in one H5P is through the use of column, but more options like an upcoming pages and another mini course content type are coming. (So if you have two Course Presentations in a mini-course they would both use the same texts)

Another thing to consider is whether or not it makes sense to share a link if the Course Presentation is being used as sub-content. I guess that would depend on the content that used the Course Presentation as sub content.

Regarding app id, you want to hard-code an app-id into Course Presentation, right? I thought an app-id was connected to a url, but I might be wrong there. As long as it works and we don't think there is a significant chance that it might stop working I'm happy.

If you agree with my points above, feel free to bake them into a pull request. As long as it has a group in semantics for social media sharing with texts, and settings for turning sharing for each platform on or off I'm happy. Also make sure you have a solid solution for the Facebook App Id that will work well when a Course Presentation is created on one site, downloaded from there and uploaded to another site. I'll make sure a pull request on this gets reviewed quickly.

**Comment by adam-p-king** [comment]
Yeah, I'll definitely implement a toggle for these and move the settings into their own group, unless you can think of a more preferable place specifically? 

As far as I can tell, Facebook have no limitations on specific domains, IPs or URLs however because they're generally owned by a specific account I was hesitant to create one myself in-case you had an account in mind to use for this. 

As far as porting a Course Presentation from one site to another, this should work off the bat with the API; As an example, Android apps could be installed on many devices but still use an App Id from some API, I assume Facebook is the same. 

Thanks for the feedback and assurance, I'll definitely be making a pull request soon but I'll spend the morning making sure the requirements are met first as you have very valid points.

**Comment by falcon-git** [comment]
I think the best place for the new sharing settings group would be at the bottom of override (behaviour settings)

Owner of the api should probably ideally be H5P. I can create one. Do I need to do anything special or just follow this procedure? https://developers.facebook.com/docs/apps/register

**Comment by adam-p-king** [comment]
Yeah that sounds good to me, I'll get that done now and pull request.

As far as I can tell, we don't actually need one; after some digging around on the Facebook developer pages: `Web: If you are using Social Plugins on the web, you do not need to create a Facebook app for integrating a Social Plugin.`. Potentially highlighting the fact that the method I've used now is going to continue being maintained.

**Comment by falcon-git** [comment]
Ah, that sounds really good!

**Comment by adam-p-king** [comment]
@falcon-git Do you know what happens to the override properties when read from the JSON object in cp.js? If I log `this.elementsOverride.params.behaviour` from `setElementsOverride`, after the overrides are processed, the object is empty. If I log the entire cp object in `summary-slide.js` I can locate the `elementsOverride.params.behaviour` object inside of it but again, it shows up empty. Sorry if I'm missing something obvious here.

**Comment by adam-p-king** [comment]
@falcon-git I've made a pull request and the rough edges have been shaved; let me know if you spot anything that needs changing or where areas could be improved and I'll be happy to make the changes!
