### ISSUE TITLE
Web Accessibility 

### ISSUE THREAD

**Issue by mgifford** [h5p/h5p-course-presentation#45]
According to http://facdev.e-education.psu.edu/instdesigner/h5p

This module isn't accessible. Is this still accurate? What efforts have been made to see that this meets WCAG 2.0 AA?

**Comment by timothyylim** [comment]
Hi @mgifford , sorry for the late response. No accessibility updates have been added to h5p-course-presentation. However, improvements to h5p-interactive-video, h5p-drag-text (Drag the Words) and h5p-drag-question (Drag and Drop) will be part of the next release.
