### ISSUE TITLE
Error tring to JSON parse and validate en.json language translation file

### ISSUE THREAD

**Issue by nadavkav** [h5p/h5p-course-presentation#51]
https://raw.githubusercontent.com/h5p/h5p-course-presentation/master/language/.en.json

trying to parse it with: http://jsoneditoronline.org
(so I can later translate it)

**Comment by timothyylim** [comment]
Seems like a stray ']' was added on line 287. Feel free to translate it without it and make sure the json validates.

**Comment by nadavkav** [comment]
Thanks
