### ISSUE TITLE
Copy/Paste doesn't work with MAC-computers

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-course-presentation#52]
Hello,

You cannot Copy and paste images in course presentation with MAC computer + Safari/Chrome/Firefox, in Windows 10 you can;

1. Select image
2. Press CTRL+C
3. Go to the slide you want and press CTRL+V to paste the image as many times as you want

This way you don't have to upload a same image every single time when you want to use it on several slides, you can just easily copy/paste it where its necessary.

**Comment by timothyylim** [comment]
It's working on H5P.org but you have to press CTRL+C not CMD+C. Could you try that?

**Comment by andreascerpus** [comment]
Works on my mac using "Ctrl + C".
Usually "Cmd + C" would be the default way to copy on a mac, so I think it would cause less confusion to add it.

**Comment by Jarvil** [comment]
Hello,

Actually I tried with browsers copy and paste -buttons, after keyboard CMD+C didn't work. But the browser buttons didn't work any better, i'm using mac mini high sierra.

**Comment by timothyylim** [comment]
Hi @Jarvil , have you tried 'CTRL-C'? i.e. not the browser buttons

**Comment by Jarvil** [comment]
Hello,

Control+C worked with MAC / Safari & Chrome but still copy/paste from browser menu doesn't work.

**Comment by timothyylim** [comment]
Thanks @Jarvil , I think adding copy and paste via the browser would be a new feature. If you could submit a feature request in the forums that would be great.
