### ISSUE TITLE
Scroll when you check question

### ISSUE THREAD

**Issue by DennisWiencken** [h5p/h5p-course-presentation#55]
When pressing "check" at a question the content gets to big for the frame and the users have to scroll in order to see the feedback. Some of the users does not realize they have to scroll and never sees the correct answer or feedback. Perhaps this could be fixed by resizing or something?

**Comment by timothyylim** [comment]
Hi @DennisWiencken, it should scroll automatically. Could I ask which questions you are referring to?

**Comment by DennisWiencken** [comment]
Hi @timothyylim, we are using the quizset with som multiple choise questions. When we have 3 options for the answer and hit the checkbutton, it does scroll down. But the feedback is in the top and when the correct answer for example is the first one the users never see it because they do not notice that they have to scroll up. Perhaps this could be fixed with some scaling of the content so that the users do not have to scroll?

**Comment by timothyylim** [comment]
Good point. Scaling content would come with added complexity but maybe it is necessary in this case. I would make a feature request on the forums:

https://h5p.org/forum/16

and hopefully others in the community who have the same problem will contribute the necessary code.
