### ISSUE TITLE
Multiple Single choice set -questions cannot be selected in Moodle

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-course-presentation#56]
Hello,

1. Create H5P course presentation
2. Add single blank choice set question, click it to confirm that you can select it
3. Add second blank single choise set and notice how you can't select it at all.
4. Select save and display
5. Edit H5P again
6. Notice that you can now select the second "single choice set" but if you a add third one you cannot select it at all before saving/editing again.

This happens in Moodle with Boost-theme, if you use Clean-theme all of the created "single choice set" -questions are stacked and you cannot select them at all before saving and editing again.

Tested with Moodle Moodle 3.3.1+ (Build: 20170810) and mod_hvp 1.5  & Single Choice Set (1.9.6) & Course Presentation Editor (1.17.4) & Boost/Clean themes.

**Comment by thomasmars** [comment]
Thanks for the report, we'll follow this up in https://github.com/h5p/h5p-single-choice-set/issues/15#issuecomment-346329417.
