### ISSUE TITLE
Cannot add interactive video in Course presentation with Boost-theme

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-course-presentation#57]
Hello,

It seems you cannot add interactive video to Course presentation in Moodle with Boost-theme, with Clean theme it works. Boost theme is the new core theme for Moodle since version 3.2

**Comment by thomasmars** [comment]
Duplicate of https://github.com/h5p/h5p-moodle-plugin/issues/183, closing this. The issue will be tracked from there.
