### ISSUE TITLE
Switch to a given slide from within an embedded iframe

### ISSUE THREAD

**Issue by pheraph** [h5p/h5p-course-presentation#62]
I posted my question already in the [forums](https://h5p.org/node/167956), but it probably better fits here:

I am currently evaluating if a Course Presentation could be used for a simple point and click adventure (with Active Surface enabled). To give me more flexibility I successfully added an iframe to a slide and loaded a small minigame. Now I am struggling to switch to a different slide from within the iframe's minigame to continue the game at a different point. I tried to call jumpToSlide() from my minigame, but it isn't working because of lots of undefined values:

```javascript
parent.window.H5P.CoursePresentation.prototype.jumpToSlide();
```

So any idea how I can use jumpToSlide() to switch to a given slide?

**Comment by timothyylim** [comment]
@pheraph , what errors do you get when you use jumpToSlide(index)?

**Comment by pheraph** [comment]
@timothyylim Thanks for your reply, really appreciate it. Here is a tiny demo with my hijacked iframe: 

http://studica.vcrp.de/h5p-dev/index.php/2018/01/10/4/

If I try to call jumpToSlide(index) I get a `TypeError: this.$current is undefined`. I had a glance at the debugger and noticed more undefined variables (n.$slidesWrapper at least). That's were I stopped because I have no idea if it is supposed to work at all that way (remember I am calling the function from an iframe).

**Comment by icc** [comment]
Try this:
```js
window.parent.H5P.instances[0].jumpToSlide(3);
```
